# Created by btngana24680 @2025
# Modified by saadelasfur @2025
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache toolchain
        uses: actions/cache@v4
        with:
          path: ./toolchain
          key: ${{ runner.os }}-toolchain-${{ hashFiles('download-deps.sh') }}-${{ hashFiles('toolchain/**/*') }}
          restore-keys: |
            ${{ runner.os }}-toolchain-${{ hashFiles('download-deps.sh') }}-
            ${{ runner.os }}-toolchain-
            ${{ runner.os }}-

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: |
            git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
            default-jdk gnupg flex bison ccache gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
            python3 make sudo bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
            make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd

      - name: Clone kernel repository
        run: |
          git clone --depth 1 --branch aosp-ksu --recurse-submodules https://github.com/AhmedAmrNabil/kernel_samsung_ascendia_sm7325.git
      
      - name: Set up build environment
        run: |
          sudo apt update && sudo apt upgrade -y
          DEBIAN_FRONTEND=noninteractive sudo apt update && sudo apt install -y git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
          default-jdk gnupg flex bison ccache gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
          python3 make sudo bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
          make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd --fix-missing && wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb
          
      - name: Run build script
        run: |
          export TERM=xterm
          chmod +x build.sh
          ./build.sh -c

      - name: Find built file
        id: find_artifact
        run: |
          ARTIFACT=$(ls build/Builds/ | head -n 1)
          KSU_VER=$(git -C kernel_samsung_ascendia_sm7325/KernelSU-Next describe --tags --abbrev=0 | head -n 1)
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          echo "KSU_VER=$KSU_VER" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: build/Builds/${{ env.ARTIFACT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.KSU_VER }}
          name: Kernel SU Next ${{ env.KSU_VER }}
          files: build/Builds/${{ env.ARTIFACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
